image: node:latest

variables:
  PUBLIC_URL: /buymecoffee

cache:
  paths:
  - node_modules

stages:
  - deploy

pages:
  stage: deploy

  script:
    - npm install
    - npm run build
    - mv public _public  # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public    # Move build files to public dir for Gitlab Page
    - cp public/index.html index/404.html
    
  artifacts:
    paths:
    - public

  only:
    - main
